###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
        image: mariadb:latest
        container_name: symbnb-mysql
        working_dir: /application
        volumes:
            - .:/application
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=dbrootpw
            - MYSQL_DATABASE=symbnb
            - MYSQL_USER=symbnb
            - MYSQL_PASSWORD=symbnbpw
        ports:
            - "8009:3306"

    webserver:
        image: nginx:alpine
        container_name: symbnb-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8010:80"

    php-fpm:
        build: phpdocker/php-fpm
        container_name: symbnb-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
volumes:
    db_data:
