version: "3.7"
services:

  database:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpw
      - MYSQL_DATABASE=symbnb
      - MYSQL_USER=symbnb
      - MYSQL_PASSWORD=symbnbpw
    expose:
      - 3306

  nginx:
    build:
      context: ./docker/nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - 8050:80
    restart: always
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx:cached
      - ./app/public:/var/www/symfony/public:cached
    depends_on:
      - php

  php:
    build:
      context: ./docker/php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    restart: always
    volumes:
      - ./app:/var/www/symfony:cached
      - /var/www/symfony/var/
      - /var/www/symfony/var/cache/
      - /var/www/symfony/var/logs/
      - /var/www/symfony/var/sessions/
    links:
      - database

  adminer:
    build:
      context: ./docker/adminer
    restart: always
    ports:
      - 8051:8080
    environment:
      ADMINER_DESIGN: ng9
    links:
      - database
volumes:
  db_data:
